export {default as Home} from './Home'
export {default as About} from './About'
export {default as CSV} from './CSV'
export {default as Tribes} from './Tribes'
export {default as NotFound} from './NotFound'
